StageDeployed19032015-Codefiles/Source/RexonaAU/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Examine;
using Newtonsoft.Json;
using RexonaAU.Models;
using System.Web.Mvc;
using umbraco.BusinessLogic;
using umbraco.cms.businesslogic.media;
using umbraco.cms.businesslogic.member;
using umbraco.cms.businesslogic.Tags;
using umbraco.cms.businesslogic.web;
using umbraco.MacroEngines;
using Tags = umbraco.editorControls.tags;
using umbraco;
namespace RexonaAU.Controllers
{
    public class ArticleController : Umbraco.Web.Mvc.SurfaceController
    {
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ArticlesSearch(string search)
        {
            ISearcher Searcher = ExamineManager.Instance.SearchProviderCollection["ArticleSearch"];
            var criteria = Searcher.CreateSearchCriteria(UmbracoExamine.IndexTypes.Content);
            var fields = new String[] { "articleAuthor", "articleTag", "articleDescription", "nodeName" };

            Examine.SearchCriteria.IBooleanOperation filter = criteria.GroupedOr(fields, search);

            var searchResults = Searcher.Search(filter.Compile()).Select(p => p.Fields);
            List<ArticleDetail> model = new List<ArticleDetail>();
            foreach (var result in searchResults)
            {
                model.Add(new ArticleDetail
                {
                    ArticleName = result["nodeName"],
                    ArticleAuthor = result["articleAuthor"],
                    ArticleDescription = result["articleDescription"].Substring(0, 500),
                    ArticleId = Convert.ToInt32(result["id"]),
                    PostedOn = result["updateDate"]
                });
              
            }
            ViewBag.ModelList = model;                
            return View("SearchResult"); 
        }

           
        public JsonResult GetArticlesByTag(string ArticlesTag)
        {
            List<ArticleDetail> articleDetail = new List<ArticleDetail>();
            var matchingNodes = Tag.GetNodesWithTags(ArticlesTag).Where(x => x.ParentId == uQuery.GetNodesByName("Articles").FirstOrDefault().Id);

            foreach (var nodeid in matchingNodes)
            {
                DynamicNode node = new DynamicNode(nodeid.Id);
                articleDetail.Add(new ArticleDetail
                {

                    ArticleName = node.Name,
                    ArticleAuthor = node.GetProperty("articleAuthor").Value,
                    PostedOn = String.Format("{0:t}", node.UpdateDate.ToString("h:mm tt   MM/dd/yyyy")),
                    ArticleDescription = node.GetPropertyValue("articleDescription").Substring(0, 500),
                    ArticleUrl = node.Url,
                });
            }
            return Json(articleDetail, JsonRequestBehavior.AllowGet);
        }

         public JsonResult GetArticles()
         {
            DynamicNode node = new DynamicNode(uQuery.GetNodesByName("Articles").FirstOrDefault().Id); // Get Pledges NodeId
            List<ArticleDetail> articleDetail = new List<ArticleDetail>();
            foreach (var childNode in node.Children)
            {
                var Type = Tag.GetNodesWithTags(childNode.GetProperty("articleTag").Value).Where(x => x.ParentId == uQuery.GetNodesByType("PledgeCategories").FirstOrDefault().Id);
                int nodId = Type.Select(p => p.Id).FirstOrDefault();
                DynamicNode color = new DynamicNode(nodId);
                articleDetail.Add(new ArticleDetail
                {

                    ArticleName = childNode.Name,
                    ArticleAuthor = childNode.GetProperty("articleAuthor").Value,
                    ArticleUrl = childNode.Url,
                    ArticleDocType = "Inspiration",
                    ArticleType = Type.Select(t => t.Text).FirstOrDefault().ToString(),
                    color = color.GetProperty("color").Value,
                    ArticleId = childNode.Id

                });
            }
            return Json(articleDetail, JsonRequestBehavior.AllowGet);
        }
    }
}

StageDeployed19032015-Codefiles/Source/RexonaAU/Controllers/LogOnController.cs
using RexonaAU.Models;
using RexonaAU.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Traction.Fusion;
using Traction.Fusion.Customers;
using Traction.Fusion.Subscriptions;
using umbraco.cms.businesslogic.member;
using umbraco;
using umbraco.NodeFactory;
using System.Security.Cryptography;
using System.IO;
using Umbraco.Core.Logging;
using System.Configuration;
using Umbraco.Core.Services;
namespace RexonaAU.Controllers
{
    public class LogOnController : Umbraco.Web.Mvc.SurfaceController
    {

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(SignUpModel model)
        {
            Member createMember = null;

            //Decrement count on register click
            //var SignUpNode = uQuery.GetNodesByType("SignUp").FirstOrDefault();
            //int CurrentDropOff;
            //if (SignUpNode != null && SignUpNode.Id > 0)
            //{
            //    CurrentDropOff = SignUpNode.GetProperty<int>("dropOffCount");
            //    SignUpNode.SetProperty("dropOffCount", CurrentDropOff - 1);
            //}

            try
            {
                bool exists = CheckExistingUser(model.Email);

                if (exists)
                {
                    Member current = Member.GetMemberFromEmail(model.Email);
                    if (current.GetProperty<bool>("facebookConnect"))
                    {
                        TempData.Remove("ErrorMessage");
                        TempData.Add("ErrorMessage", "<strong>Error.</strong><br><br>An account with the entered Email already exists.<br>Please Sign In using Facebook.");

                    }
                    else
                    {
                        TempData.Remove("ErrorMessage");
                        TempData.Add("ErrorMessage", "<strong>Error.</strong><br><br>An account with the entered Email already exists.<br>Please Sign In to continue.");
                    }
                    return RedirectToCurrentUmbracoPage();
                }
                else
                {
                    MemberType demoMemberType = MemberType.GetByAlias("RexonaPledgeUser"); //id of membertype ‘Rexona’

                    createMember = Member.MakeNew(model.FirstName + ' ' + model.LastName, model.Email, model.Email, demoMemberType, new umbraco.BusinessLogic.User(0));
                    //var firstname = model.UserName.Split(' ')[0];
                    //var lastname = model.UserName.IndexOf(' ') > -1 ? model.UserName.Remove(0, model.UserName.IndexOf(' ') + 1) : " ";

                    //createMember.getProperty("firstName").Value = model.FirstName;
                    //createMember.getProperty("lastName").Value = model.LastName;
                    //createMember.getProperty("displayName").Value = model.DisplayName;

                    ////createMember.getProperty("birthDate").Value = model.DateOfBirth;
                    //createMember.getProperty("birthDate").Value = Convert.ToDateTime(model.DateOfBirth).ToString("dd MMMM yyyy");
                    //createMember.getProperty("postCode").Value = model.PostCode;
                    createMember.getProperty("subscribedForDoMOre").Value = model.Subscribe;
                    createMember.getProperty("facebookConnect").Value = model.FacebookConnect;
                    createMember.SetProperty("termsConditions", 1);
                    //string capitalValues = ConfigurationManager.AppSettings[model.State];
                    //model.CapitalCity = capitalValues.Split(',')[0];
                   // model.CapitalPostCode = capitalValues.Split(',')[1];

                    //createMember.getProperty("state").Value = model.State;
                    //createMember.getProperty("capitalCity").Value = model.CapitalCity;
                    //createMember.getProperty("capitalPostCode").Value = model.CapitalPostCode;

                    createMember.Password = model.Password;

                    //track last login date
                    createMember.SetProperty("lastLoginDate", DateTime.Now.ToString("dd/MM/yyyy HH:mm tt"));

                    createMember.Save();


                    Session["SignUp"] = true;

                    SignInModel loginmodel = new SignInModel();
                    loginmodel.EmailAddress = model.Email;
                    loginmodel.Password = model.Password;

                    setAuthentication(loginmodel.EmailAddress, false);


                }
            }
            catch (Exception ex)
            {
                LogHelper.Info(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType, "Rexona AUS : SignUp() method failed during execution. Stack Trace: " + ex.StackTrace);
                TempData.Remove("ErrorMessage");
                TempData.Add("ErrorMessage", "<strong>Oops.</strong><br><br>Something went wrong. Please try again.");

            }
            return RedirectToCurrentUmbracoPage();
        }

        [HttpPost]
        public JsonResult SignIn(string email, string password)
        {
            try
            {

                var checkMember = Member.GetMemberFromEmail(email);

                //Check the member exists
                if (checkMember != null)
                {
                    //Get the member from their email address and password
                    var attemptLogin = Member.GetMemberFromLoginNameAndPassword(checkMember.LoginName, password);

                    if (attemptLogin != null)
                    {
                        //track last login date
                        attemptLogin.SetProperty("lastLoginDate", DateTime.Now.ToString("dd/MM/yyyy HH:mm tt"));

                        setAuthentication(email, false);
                        int count = getMemberPledgeCount(attemptLogin);

                        if (count == 0)
                        {
                            return Json("NoPledges", JsonRequestBehavior.AllowGet);
                        }
                     
                    }
                    else
                    {
                        //TempData.Remove("Status");
                        //TempData["Status"] = "<strong>Error.</strong><br><br>Invalid username or password";
                        return Json("Invalid", JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    //TempData.Remove("Status");
                    //TempData["Status"] = "<strong>Error.</strong><br><br>Invalid username or password";
                    return Json("NotSignedUp", JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                LogHelper.Info(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType, "Rexona AUS : Signin() method failed during execution. Stack Trace: " + ex.StackTrace);
                TempData.Remove("ErrorMessage");
                TempData.Add("ErrorMessage", "<strong>Oops.</strong><br><br>Something went wrong. Please try again.");
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
            return Json("Success", JsonRequestBehavior.AllowGet);

        }


        private void setAuthentication(string Email, bool isFbUser)
        {
            HttpCookie cookie = null;
            FormsAuthenticationTicket authTicket = null;

            authTicket = new FormsAuthenticationTicket(1, Email, DateTime.Now, DateTime.Now.AddMinutes(30), false, string.Empty, FormsAuthentication.FormsCookiePath);

            //encrypt the ticket and add it to a cookie
            cookie = new HttpCookie(FormsAuthentication.FormsCookieName, FormsAuthentication.Encrypt(authTicket));
            Response.Cookies.Add(cookie);
            if (!isFbUser && Convert.ToBoolean(Session["SignUp"]))
            {
                Node nextNode = uQuery.GetNodesByType("MyDashboard").FirstOrDefault();
                if (nextNode != null && nextNode.Id > 0 && !Convert.ToBoolean(Session["SignUp"]))
                {
                    Response.Redirect(nextNode.Url);
                }
                else
                {
                    //nextNode = uQuery.GetNodesByType("PledgeSteps").LastOrDefault();
                    nextNode = uQuery.GetNodesByType("MyDashboard").LastOrDefault();
                    if (nextNode != null && nextNode.Id > 0)
                    {
                        Response.Redirect(nextNode.Url);
                    }
                    Session["SignUp"] = false;
                }
            }
        }

        [HttpPost]
        public ActionResult Logout()
        {
            var url = "";
            try
            {

                //Member already logged in, lets log them out and redirect them home
                if (Member.IsLoggedOn())
                {
                    //Log member out
                    FormsAuthentication.SignOut();
                    Session.Abandon();

                    //Redirect home
                    Node nextNode = uQuery.GetNodesByType("Login").FirstOrDefault();
                    if (nextNode != null && nextNode.Id > 0)
                    {
                        url = nextNode.Url;
                    }
                }
                else
                {
                    //Redirect home
                    Node nextNode = uQuery.GetNodesByType("Master").FirstOrDefault();
                    if (nextNode != null && nextNode.Id > 0)
                    {
                        url = nextNode.Url;
                    }
                }
            }
            catch (Exception ex)
            {
                LogHelper.Info(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType, "Rexona AUS : Logout() method failed during execution." + Environment.NewLine + "Message: " + ex.Message + Environment.NewLine + "Stack Trace: " + ex.StackTrace);
            }

StageDeployed19032015-Codefiles/Source/RexonaAU/Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using umbraco.NodeFactory
@{
    Layout = "_Baselayout.cshtml";
    string pledgeStepurl = uQuery.GetNodesByType("PledgeSteps").FirstOrDefault().NiceUrl;
}
<div class="hero-panel about">
    <div class="row">
        <div class="large-6 columns">
            <div class="row">
                <div class="large-12 columns">
                    <h1 class="contained-title">Rules of the pre-game</h1>
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <p class="subheader inverted">@Umbraco.Field("getStartedDescription")</p>
                    <a href="@pledgeStepurl" class="button with-icon right-icon">Set your goal <i class="fa fa-chevron-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="content-panel">
    <div class="row">
        <div class="large-6 medium-6 small-12 columns">
            <img src="@Umbraco.Field("setGoalImage")" alt="@Umbraco.Field("goalImageAltText")">
        </div>
        <div class="large-6 medium-6 small-12 columns">
            <h2 class="contained-title">ETCH YOUR GOAL IN STEEL</h2>
            <p class="subheader">@Umbraco.Field("setGoalDescription")</p>

        </div>
    </div>
</div>
<div class="content-panel">
    <div class="row">
        <div class="large-6 medium-6 small-12 columns">
            <h2 class="contained-title inverted">Discussions</h2>
            <p class="subheader">@Umbraco.Field("discussionsDescription")</p>
        </div>
        <div class="large-6 medium-6 small-12 columns">
            <img src="@Umbraco.Field("discussionsImage")" alt="@Umbraco.Field("discussionImageAltText")">
        </div>
    </div>
</div>
<div class="content-panel">
    <div class="row">
        <div class="large-6 medium-6 small-12 columns">
            <img src="@Umbraco.Field("eventsImage")" alt="@Umbraco.Field("eventImageAltText")">
        </div>
        <div class="large-6 medium-6 small-12 columns">
            <h2 class="contained-title">Events</h2>
            <p class="subheader">@Umbraco.Field("eventsDescription")</p>
        </div>
    </div>
</div>
<div class="content-panel">
    <div class="row">
        <div class="large-6 medium-6 small-12 columns">
            <h2 class="contained-title inverted">Useful Links</h2>
            <p class="subheader">@Html.Raw(Umbraco.Field("usefulLinks"))</p>
        </div>
    </div>
</div>


@*will be hidden for 1st release*@
@*hidden in release 1*@
<div class="content-panel has-border" style="display:none;">
    <div class="row">
        <div class="large-6 columns">
            <h2 class="contained-title inverted">Popular Goals</h2>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <div class="masonry-wall">
                <div class="item is-pledge">
                    <a href="#">
                        <img src="~/images/pledge-th.jpg" class="full-on-mobile">
                    </a>
                    <div class="item-content inverted">
                        <div class="item-details">
                            <div class="item-description">
                                <p>1,245 other people have made this pledge</p>
                            </div>
                        </div>
                        <div class="item-actions">

                            <div class="item-share">
                                <a href="#" class="small-link">Share</a>
                            </div>

                            <div class="item-join">
                                <a href="#" class="small-link">Join</a>
                            </div>

                            <div class="item-rate">
                                <div class="rating-icon">
                                    <i class="fa fa-heart"></i>
                                </div>
                                <div class="rating-number">
                                    <span>4</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item is-pledge">
                    <a href="#">
                        <img src="~/images/pledge-th.jpg" class="full-on-mobile">
                    </a>
                    <div class="item-content inverted">
                        <div class="item-details">
                            <div class="item-description">
                                <p>1,245 other people have made this pledge</p>
                            </div>
                        </div>
                        <div class="item-actions">

                            <div class="item-share">
                                <a href="#" class="small-link">Share</a>
                            </div>

                            <div class="item-join">
                                <a href="#" class="small-link">Join</a>
                            </div>

                            <div class="item-rate">
                                <div class="rating-icon">
                                    <i class="fa fa-heart"></i>
                                </div>
                                <div class="rating-number">
                                    <span>4</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item is-pledge">
                    <a href="#">
                        <img src="~/images/pledge-th.jpg" class="full-on-mobile">
                    </a>
                    <div class="item-content inverted">
                        <div class="item-details">
                            <div class="item-description">
                                <p>1,245 other people have made this pledge</p>
                            </div>
                        </div>
                        <div class="item-actions">

                            <div class="item-share">
                                <a href="#" class="small-link">Share</a>
                            </div>

                            <div class="item-join">
                                <a href="#" class="small-link">Join</a>
                            </div>

                            <div class="item-rate">
                                <div class="rating-icon">
                                    <i class="fa fa-heart"></i>
                                </div>
                                <div class="rating-number">
                                    <span>4</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item is-pledge">
                    <a href="#">
                        <img src="~/images/pledge-th.jpg" class="full-on-mobile">
                    </a>
                    <div class="item-content inverted">
                        <div class="item-details">
                            <div class="item-description">
                                <p>1,245 other people have made this pledge</p>
                            </div>
                        </div>
                        <div class="item-actions">

                            <div class="item-share">
                                <a href="#" class="small-link">Share</a>
                            </div>

                            <div class="item-join">
                                <a href="#" class="small-link">Join</a>
                            </div>

                            <div class="item-rate">
                                <div class="rating-icon">
                                    <i class="fa fa-heart"></i>
                                </div>
                                <div class="rating-number">
                                    <span>4</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StageDeployed19032015-Codefiles/Source/RexonaAU/Views/ForgotPassword.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using umbraco.NodeFactory;
@{
    Layout = null;
    
    //Redirect all request to next page
    Node forgottenPassword = uQuery.GetNodesByType("ForgotPassword-Step-1").FirstOrDefault();
    if (forgottenPassword != null && forgottenPassword.Id > 0)
    {
        Response.Redirect(forgottenPassword.NiceUrl);
    }
}

StageDeployed19032015-Codefiles/Source/RexonaAU/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using RexonaAU.Helpers;
@using umbraco.NodeFactory;
@{
    Layout = "_Baselayout.cshtml";

    string forgottenPasswordURL = string.Empty;
    Node forgottenPassword = uQuery.GetNodesByType("ForgotPassword-Step-1").FirstOrDefault();
    if (forgottenPassword != null && forgottenPassword.Id > 0)
    {
        forgottenPasswordURL = forgottenPassword.NiceUrl;
    }
    Common.SetNoBrowserCacheForpage();
    Common.CheckUserSessionValidity();
}

@*<div class="row top-row">

    <div class="large-5 columns large-centered">
        <h1>@Umbraco.Field("pageTitle")</h1>
       <p>@Umbraco.Field("pageDescription")</p>
    </div>
</div>

@Html.Partial("_SignIn", new RexonaAU.Models.SignInModel())   *@

@Html.Action("RenderLogin", "LogOn")

StageDeployed19032015-Codefiles/Source/RexonaAU/Views/PledgeCategory.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "_Baselayout.cshtml";
}
@{
    var imageID = Umbraco.Field("image").ToString();
    int MediaimageID = Convert.ToInt32(imageID);
    var media = new umbraco.cms.businesslogic.media.Media(MediaimageID);
    var Title = Model.Content.Name;
    var Description = Model.Content.GetPropertyValue("Description");
    var ArticlesTag = Model.Content.GetPropertyValue("categoryTag");
    if (media != null)
    {
        var ImageSource = media.getProperty("umbracoFile").Value;     

 <div class="category-header" style="background-image: url('@ImageSource');">
        <div class="row top-row">
          
          <div class="large-6 columns">
            <a href="/empowerment" class="crumb-back">« Back to Empowerment</a>
            <h1>@Title</h1> 
            <p>@Description </p> 
             @using (Html.BeginUmbracoForm<RexonaAU.Controllers.ArticleController>("ArticlesSearch"))
             {
                <input type="text" name="search" placeholder="Search @Title..." id="txtArticleSearch">                 
                @Html.AntiForgeryToken() 
             }
          </div>
        </div>
      </div>
    }
}

<div class="alternate-panel noMargin">
  <div class="row">
    <div class="large-8 columns" id="articleResults">
         </div>
    </div>  
</div>
    <script>

        $(document).ready(function () {
            $.ajax({
                url: "@Url.Action("GetArticlesByTag", "Article")?ArticlesTag=" + '@ArticlesTag',
                contentType: 'application/json; charset=utf-8',
                type: 'POST',
                dataType: 'json'
            })

                             .success(function (result) {
                                 var items = '';
                                 for (var i in result) {
                                     //console.log(result);
                                     items += '<article><a href="' + result[i].ArticleUrl + '"><h2>' + result[i].ArticleName + '</h2></a><div class="author">by ' + result[i].ArticleAuthor + '</div><div class="posted"> POSTED ' + result[i].PostedOn + '</div><hr>' + result[i].ArticleDescription + '<a href="' + result[i].ArticleUrl + '" class="readMore"><br/><br/>Read More</a></article>';
                                 }

                                 $('#articleResults').html(items);

                             })
                              .error(function (result) {
                                  alert("Inside Error");
                              })


        });

    </script>

         

StageDeployed19032015-Codefiles/Source/RexonaAU/Views/SearchResult.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "_Baselayout.cshtml";
}

@Html.Partial("_ArticleSearch");

StageDeployed19032015-Codefiles/Source/RexonaAU/Views/SignUp.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using RexonaAU.Helpers;
@{
    Layout = "_Baselayout.cshtml";
    Common.SetNoBrowserCacheForpage();
    Common.CheckUserSessionValidity();
}

@Html.Action("RenderRegister", "LogOn")